// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

// Product defines model for Product.
type Product struct {
	Id       int64 `json:"id"`
	Quantity int   `json:"quantity"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// PostApiOrdersJSONBody defines parameters for PostApiOrders.
type PostApiOrdersJSONBody struct {
	Products []Product `json:"products"`
	UserId   int64     `json:"user_id"`
}

// PostApiUsersJSONBody defines parameters for PostApiUsers.
type PostApiUsersJSONBody struct {
	Age       int    `json:"age"`
	FirstName string `json:"first_name"`
	IsMarried bool   `json:"is_married"`
	LastName  string `json:"last_name"`
	Password  string `json:"password"`
}

// PostApiOrdersJSONRequestBody defines body for PostApiOrders for application/json ContentType.
type PostApiOrdersJSONRequestBody PostApiOrdersJSONBody

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody PostApiUsersJSONBody
