openapi: 3.0.0
info:
  title: User and Order API
  description: API for creating users and orders.
  version: "1.0.0"
servers:
  - url: http://localhost:8080

paths:
  /api/users:
    post:
      summary: Create a new user
      description: Register a new user with personal details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - age
                - is_married
                - password
              properties:
                first_name:
                  type: string
                  maxLength: 100
                last_name:
                  type: string
                  maxLength: 100
                age:
                  type: integer
                  minimum: 18
                is_married:
                  type: boolean
                password:
                  type: string
                  maxLength: 255
      responses:
        '201':
          description: User created successfully.
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  /api/orders:
    post:
      summary: Place a new order
      description: Submit a new order with product details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - products
              properties:
                user_id:
                  type: integer
                  format: int64
                products:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Order created successfully.
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - quantity
      properties:
        id:
          type: integer
          format: int64
        quantity:
          type: integer
          minimum: 1

  responses:
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                required:
                  - code
                  - message
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
